### ISSUE TITLE
Entry added two times to /etc/subuid

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd-pkg-ubuntu#19]
/etc/subuid looked like this:
```
root:110000:500000000
```

Than apt-get install lxd, and now there is a new entry as well:
```
root:500110000:65536
```

Ubuntu Xenial.

**Comment by stgraber** [comment]
If that second entry matches the range added for the "lxd" user, then that's intentional.

**Comment by stgraber** [comment]
One user can have multiple id allocations. We assign an allocation to the lxd user and then replicate it to the root user so LXD can actually use it. We don't use or alter any existing allocation.

**Comment by tomposmiko** [comment]
A bit complicated to me, but fair enough:)
