### ISSUE TITLE
Update usr.sbin.dnsmasq profile for network api

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd-pkg-ubuntu#21]
Possible solution:
add `/var/lib/lxd/networks/** rw,` to usr.sbin.dnsmasq profile
Without no network will start.
Long version:
Currently dnsmasq profile includes extra rights for lxd.
```
  # lxd-bridge pid and lease files
  /{,var/}run/lxd-bridge/dnsmasq.pid   rw,
  /var/lib/lxd-bridge/dnsmasq.*.leases rw,

```
Better solution will be to make `#include <abstractions/lxdsomething>` in upstream for dnsmasq (could take longer then expected), however lxd api is still only in git, and profile works ok for repository version obviously. Heh!
Another more raw, but simple solution will be to pack own dnsmasq profile with lxd or make posintall profile editing and reloading. Obviously fixing ppa package is not a problem at all, but this slight issue should be taken in count when new lxd with network api will come out in official repository. Since, I bet no one want to lose network in containers with upgrade. :8ball: 

```
Info:  
Ubuntu xenial and lxd from lxd-git-master from localhost:
 certificate fingerprint: d1f6f03fa58795d62a7141005e95d3b76af87e2e0c4ef07f45e018b24a0105e7
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-41-generic
  server: lxd
  serverpid: 3322
  serverversion: "2.3"
  storage: zfs
  storageversion: "5"
config:
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false
```

**Comment by stgraber** [comment]
The dnsmasq apparmor profile isn't shipped by default on Ubuntu systems. It's only present if the user manually installs the apparmor-profiles package.

Can you please file a bug about this at https://launchpad.net/ubuntu/+source/apparmor/+filebug and I'm sure someone on the apparmor team (who maintains that unofficial profile) will be happy to update it.

**Comment by stgraber** [comment]
It's against Ubuntu and Debian packaging policies for a package to alter a file shipped by another one so there isn't anything we can do about this in the LXD packaging.
