### ISSUE TITLE
lxd.lxc snap: container creation/deletion: error: The 'btrfs' tool isn't available

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd-pkg-ubuntu#24]
* Distribution: ubuntu
 * Distribution version: 16.10 i686
* lxd installed in snap

lxd.lxc info
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 172.16.99.16:8443
  - 172.17.10.1:8443
  - 172.17.22.1:8443
  - 172.17.11.1:8443
  - 172.17.12.1:8443
  - 172.18.0.1:8443
  architectures:
  - i686
  certificate: |
[...]
    certificatefingerprint: 78437545ab66ba6a7f1f2c9aaf051c791d409ad35873d295e8d3fc68c139928e
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: i686
  kernelversion: 4.8.0-30-generic
  server: lxd
  serverpid: 2615
  serverversion: 2.6.2
  storage: dir
  storageversion: ""
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false

filesystem: btrfs
dpkg -l btrfs* : 

  btrfs-progs                                     4.7.3-1                      i386                         Checksumming Copy on Write Filesystem utilities
ii  btrfs-tools                                     4.7.3-1                      i386                         transitional dummy package

# Issue description
for each container creation/deletion i have this message:

error: The 'btrfs' tool isn't available

# Steps to reproduce

 1. install lxd in with snap : snap install lxd
 2. configure lxd with lxd init
 3. using dir (=btrfs) as filesystem
4. create a container:
4.1: create a profile 'front'
name: front
config: {}
description: ""
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: lxdbr1
    type: nic
  eth2:
    name: eth2
    nictype: bridged
    parent: lxdbr2
    type: nic

4.2 create a container 
lxd.lxc image list images: ubuntu/yak : 
ubuntu/yakkety (3 more)         | 158ce137859a | yes    | Ubuntu yakkety i386 (20161217_03:49)    | i686    | 81.14MB | Dec 17, 2016 at 12:00am (UTC)

lxd.lxc launch 158ce137859a  xxxx -p front

results:
 container created with error:
error: The 'btrfs' tool isn't available

lxd.lxc list
+----------+-------+------+------+------------+-----------+
|   NAME   | STATE | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+----------+-------+------+------+------------+-----------+
| xxxx   | ERROR |      |      | PERSISTENT |           |
+----------+-------+------+------+------------+-----------+

can't delete it:
lxd.lxc delete xxxx
error: The 'btrfs' tool isn't available

no new btrfs subvolume created:

sudo btrfs sub list /
ID 257 gen 10984 top level 5 path @
ID 258 gen 10957 top level 5 path @home

**Comment by stgraber** [comment]
Thanks for the report. Looks like there are two issues here.

The first is that we should probably include the btrfs tools in the snap so that folks using btrfs on their system can benefit from it.

The second is that LXD shouldn't attempt to use btrfs when the tools aren't available and should just be using plain old directories in that case...

**Comment by gaetanquentin** [comment]
@stgraber 
since the btrfs tools are still installed in the system why snap applications do not see it?

**Comment by stgraber** [comment]
Because snaps don't see your system, they run in a separate, minimal read-only system.

**Comment by gaetanquentin** [comment]
OK. Thanks for tour  answer.

**Comment by stgraber** [comment]
Filed https://github.com/lxc/lxd/issues/2748 to track the LXD side of this.
