### ISSUE TITLE
LXD daemon failing to start on fresh install of Ubuntu Core 16

### ISSUE THREAD

**Issue by xanderked** [lxc/lxd-pkg-ubuntu#26]
Just installed Ubuntu Core 16 on RP3.  Installed snap package 'lxd' which installed lxd ver 2.7.

When attempting to run 'lxd init', get the error:
error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory

When attempting to run any 'lxc' commands ('lxc init ubuntu:16.04' or 'lxc info'), given message:  
LXD socket not found; is LXD installed and running?

LXD daemon fails to start with system.

Note, this is my first experience using Ubuntu Core.  I migrated from other "unsupported" versions of Ubuntu on the RP3 due to an update breaking LXD (haven't figured out which update caused the issue).

Thanks for the help!

Requested info:

uname -r
4.4.0-1030-raspi2

dmesg output:
[  981.489934] audit: type=1400 audit(1484064959.200:12): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.lxd.benchmark" pid=4283 comm="apparmor_parser"
[  982.227406] audit: type=1400 audit(1484064959.940:13): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.lxd.daemon" pid=4285 comm="apparmor_parser"
[  983.174187] audit: type=1400 audit(1484064960.884:14): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.lxd.lxc" pid=4287 comm="apparmor_parser"
[  983.910857] audit: type=1400 audit(1484064961.620:15): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.lxd.lxd" pid=4289 comm="apparmor_parser"
[  986.147749] systemd[1]: snapd.refresh.timer: Adding 5h 21min 58.509113s random time.
[  987.212685] systemd[1]: snapd.refresh.timer: Adding 4h 31min 51.022176s random time.
[  987.789631] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1034.595478] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1080.096986] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1125.602248] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1171.347545] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1216.845182] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1262.343016] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1307.849765] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1353.597543] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1399.341524] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1444.838000] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1490.354874] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1536.098764] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1581.846749] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1627.598682] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1673.347384] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1718.851187] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1764.589811] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1810.093698] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1855.594175] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1901.089938] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1946.591224] cgroup: new mount options do not match the existing superblock, will be ignored
[ 1992.093894] cgroup: new mount options do not match the existing superblock, will be ignored
[ 2037.590359] cgroup: new mount options do not match the existing superblock, will be ignored

No daemon log available

Starting daemon with --debug:
alexk1@localhost:~$ sudo lxd --debug
INFO[01-10|16:35:35] LXD 2.7 is starting in normal mode       path=/var/snap/lxd/common/lxd
WARN[01-10|16:35:35] Couldn't find the CGroup CPUset controller, CPU pinning will be ignored.
WARN[01-10|16:35:35] Couldn't find the CGroup pids controller, process limits will be ignored.
INFO[01-10|16:35:35] Default uid/gid map:
INFO[01-10|16:35:35]  - u 0 1000000 1000000000
INFO[01-10|16:35:35]  - g 0 1000000 1000000000
DBUG[01-10|16:35:35] Init                                     driver=storage/dir
INFO[01-10|16:35:35] Starting /dev/lxd handler
INFO[01-10|16:35:35] Expiring log files
DBUG[01-10|16:35:35] Looking for existing certificates        cert=/var/snap/lxd/common/lxd/server.crt key=/var/snap/lxd/common/lxd/server.key
INFO[01-10|16:35:35] Done expiring log files
**hangs here**

**Comment by stgraber** [comment]
So there are two issues when running on Ubuntu Core with Rpi3.

1) You need to manually create the LXD group or lxd won't start... "sudo groupadd --system --extrausers lxd" should take care of that.
2) The Rpi3 doesn't have a lot of entropy and so LXD can take several minutes to start initially as it's generating keys.

So I'd recommend you run:
 - sudo snap remove lxd
 - sudo groupadd --system --extrausers lxd
 - sudo snap install lxd
 - Then try "sudo lxd init" every minute or so. You can check if the lxd daemon is starting in "ps faux". If it's listed there, it's most likely still generating your keys.

**Comment by xanderked** [comment]
Great, thanks.  I'll try it out in a few days when I get back from
travelling and report back.

**Comment by xanderked** [comment]
You're solution worked, thanks.

Unfortunately I am dealing with attempting to add my username to the lxd
group; however in Ubuntu Core /etc/group is read only (design intention, I
gather) and I can't use usermod to add a supplementary group.  Still
working on a satisfactory solution, however using sudo allows me to do what
I need to do.

Thanks again.

**Comment by stgraber** [comment]
I changed the LXD snap to only rely on the lxd group if it's present. On systems that don't have it, LXD will only be accessible by the root user.

As for your case. I believe you should be able to manually modify the files under /var/lib/extrausers to add your user to the lxd group.
