### ISSUE TITLE
unable to create a btrfs storage pool

### ISSUE THREAD

**Issue by mjrider** [lxc/lxd-pkg-ubuntu#28]
# Required information

 * Distribution: Debian 
 * Distribution version: Stretch
lxd is installed with snap
relevant version info
installed:   git-3de9113 (2494) 12MB -
refreshed:   2017-06-16 11:21:26 +0200 CEST
i also tried 2417(stable)

 * The output of "lxc info" or if that fails:
runtime/cgo: config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: [REMOVED}
  certificate_fingerprint: 796b996e5acef6fc7c9ef852d03a66f3631a1a0265a792a9026aead568abb81f
  driver: lxc
  driver_version: 2.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-0.bpo.2-amd64
  server: lxd
  server_pid: 4503
  server_version: "2.14"
  storage: ""
  storage_version: ""

# Issue description
i tried to create a btrfs storage pool
i tried it in various ways
lxd init, with a prepared btrfs filesystem
lxd init with a clean blockdevice

A brief description of what failed or what could be improved.

# Steps to reproduce
with a prepared and mounted btrfs filesystem:
# lxd init 
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs) [default=dir]: btrfs
Create a new BTRFS pool (yes/no) [default=yes]? no
Name of the existing BTRFS pool or dataset: /var/lib/lxd
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? no
Would you like to create a new network bridge (yes/no) [default=yes]? no
error: existing path is neither a BTRFS subvolume nor does it reside on a BTRFS filesystem

fresh created lv
# lxd init 
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs) [default=dir]: btrfs
Create a new BTRFS pool (yes/no) [default=yes]? 
Would you like to use an existing block device (yes/no) [default=no]? yes
Path to the existing block device: /dev/debian-vg/lxd
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? no
Would you like to create a new network bridge (yes/no) [default=yes]? no
error: Failed to create the BTRFS pool: 

# Information to attach
with a prepared filesystem no logging has been found why it fails
with a blockdevice the follwing strace output was explaining the problem
```
[pid  4518] stat("/dev/debian-vg/lxd", {st_mode=S_IFBLK|0660, st_rdev=makedev(253, 8), ...}) = 0
[pid  4518] stat("/snap/lxd/2494/usr/sbin/mkfs.btrfs", 0xc82016a1d8) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/snap/lxd/2494/usr/bin/mkfs.btrfs", 0xc82016a448) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/snap/lxd/2494/sbin/mkfs.btrfs", 0xc82016a518) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/snap/lxd/2494/bin/mkfs.btrfs", 0xc82016a5e8) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/usr/sbin/mkfs.btrfs", 0xc82016a6b8) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/usr/bin/mkfs.btrfs", 0xc82016a788) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/sbin/mkfs.btrfs", 0xc82016a858) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/bin/mkfs.btrfs", 0xc82016a928) = -1 ENOENT (No such file or directory)
[pid  4518] stat("/usr/games/mkfs.btrfs", 0xc82016a9f8) = -1 ENOENT (No such file or directory)

```

**Comment by brauner** [comment]
@mjrider, do you have the btrfs tools installed? If not, please do and try again.

**Comment by mjrider** [comment]
yes i have the btrfs tools installed, but what i understood from a previous issue #24, the system installed tools are not available from the application running inside a snap.

**Comment by brauner** [comment]
Yeah, if that's true then you should use the `dir` backend.

**Comment by mjrider** [comment]
mmm thats a shame, 
the btrfs tool is available in the snap if i see it correctly, just not mkfs.btrfs
that is why i tried to use a preformated btrfs filesystem, but that didn't work either, while the tool btrfs is available

**Comment by brauner** [comment]
LXD will not allow you to use `/var/lib/lxd` itself a btrfs filesystem that would likely break all kinds of things. If  `/var/lib/lxd` resides on a btrfs filesystem you should instead give the full path to the `storage-pools` subdirectory, i.e. `/var/lib/lxd/storage-pools/` and that should work. Or, you just point it to a block device that you prepared.

**Comment by mjrider** [comment]
so, if i manual, mount btrfs filesystem under the storage-pools (/var/snap/lxd/common/lxd/storage-pools/lxd), and then run lxd init it should work ?
or do i need to create the storage pool configuration by hand?

**Comment by brauner** [comment]
No you don't need to create it by hand. Just place the `storage-pools` folder on a btrfs volume and pass that path to lxd init or do `lxc storage create lxd btrfs source=<path-to-storage-pools-subdir>`.

**Comment by stgraber** [comment]
@brauner we're talking snap here, things are pretty different. The snap doesn't see the real host filesystem.

**Comment by stgraber** [comment]
@mjrider in the snap world, /var/lib/lxd is replaced by /var/snap/lxd/current/common/lxd and indeed since LXD 2.9, we have the new storage-pools thing in place which makes things a bit different too.

I think that what you're saying is right, do:
 - mkdir -p /var/snap/lxd/common/lxd/storage-pools/default
 - Mount your btrfs filesystem on /var/snap/lxd/common/lxd/storage-pools/default
 - Run "lxd init":
   - Make sure to choose "default" as the pool name (should be the default value)
   - "btrfs" as the type
   - say "no" to creating a new pool
   - enter "/var/snap/lxd/common/lxd/storage-pools/default" as the existing pool

That should then use the btrfs filesystem you pre-mounted into place.

**Comment by stgraber** [comment]
btrfs-tools is present in the snap and I've actually tested the LXD snap to work with btrfs earlier this week

**Comment by mjrider** [comment]
i could recheck it when i'm home, but iirc the bin folder has the 'btrfs' as binary, but not mkfs.btrfs binary
i'll check your instructions for manual configuration tonight

**Comment by mjrider** [comment]
i checked for the  mkfs binary
 ```
find  | grep btrfs
./bin/btrfs
```

**Comment by mjrider** [comment]
root@nas:/snap/lxd/current# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs) [default=dir]: btrfs
Create a new BTRFS pool (yes/no) [default=yes]? no
Name of the existing BTRFS pool or dataset: /var/snap/lxd/common/lxd/storage-pools/default 
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? no
Would you like to create a new network bridge (yes/no) [default=yes]? no
***LXD has been successfully configured.***

victory!

**Comment by brauner** [comment]
:) We need to look into getting `mkfs.btrfs` enabled in the snap.

**Comment by brauner** [comment]
@mjrider, aaaaaand done. :)

**Comment by rldleblanc** [comment]
Trying to add a second btrfs storage-pool. Can you tell me what I'm doing wrong?
```
~$ mount | egrep "hdd|ssd"
/dev/sdc4 on /var/snap/lxd/common/lxd/storage-pools/ssd type btrfs (rw,relatime,ssd,space_cache,subvolid=1642,subvol=/lxd)
/dev/sdb on /var/snap/lxd/common/lxd/storage-pools/hdd type btrfs (rw,relatime,space_cache,subvolid=8436,subvol=/lxd)
~$ lxc storage create hdd btrfs source=/var/snap/lxd/common/lxd/storage-pools/hdd
Error: Failed to run: btrfs subvolume create /var/snap/lxd/common/lxd/storage-pools/hdd: ERROR: target path already exists: /var/snap/lxd/common/lxd/storage-pools/hdd
~$ lxc storage list
+------+-------------+--------+--------------------------------------------+---------+
| NAME | DESCRIPTION | DRIVER |                   SOURCE                   | USED BY |
+------+-------------+--------+--------------------------------------------+---------+
| ssd  |             | btrfs  | /var/snap/lxd/common/lxd/storage-pools/ssd | 1       |
+------+-------------+--------+--------------------------------------------+---------+
```

**Comment by rldleblanc** [comment]
Okay I found https://github.com/lxc/lxd/issues/3020, and that seems to work.

```
~$ lxc storage create hdd btrfs source=/mnt/storage/lxd
Storage pool hdd created
~$ lxc storage list
+------+-------------+--------+--------------------------------------------+---------+
| NAME | DESCRIPTION | DRIVER |                   SOURCE                   | USED BY |
+------+-------------+--------+--------------------------------------------+---------+
| hdd  |             | btrfs  | /mnt/storage/lxd                           | 0       |
+------+-------------+--------+--------------------------------------------+---------+
| ssd  |             | btrfs  | /var/snap/lxd/common/lxd/storage-pools/ssd | 1       |
+------+-------------+--------+--------------------------------------------+---------+
~# btrfs sub list /mnt/storage/
...
ID 8441 gen 126671 top level 5 path lxd
ID 8442 gen 126668 top level 8441 path lxd/containers
ID 8443 gen 126669 top level 8441 path lxd/snapshots
ID 8444 gen 126670 top level 8441 path lxd/images
ID 8445 gen 126671 top level 8441 path lxd/custom
```
