### ISSUE TITLE
AMRHF snap build of lxd is missing lxd-images script

### ISSUE THREAD

**Issue by chuckbutler** [lxc/lxd-pkg-ubuntu#3]
By default with the provided snap, I haven't been able to successfully import any images, as it appears the lxd snap is missing lxd-images script.

    (RaspberryPi2)ubuntu@rpi1:~$ lxd-images import ubuntu trusty arhmf --alias ubuntu
    -bash: lxd-images: command not found

**Comment by stgraber** [comment]
ah yeah, we probably ought to include lxd-images in there.

I tested it with:

    lxc remote add images images.linuxcontainers.org
    lxc launch images:ubuntu/trusty/armhf blah

**Comment by chuckbutler** [comment]
ah excellent. i fetched the lxd-images script and it failed out with unable to find a running lxd service. 

I'll re-test with the above suggested work around. Thanks @stgraber

**Comment by stgraber** [comment]
Fixed in 0.15 snap.
