### ISSUE TITLE
Publish a LXD 2.0 LTS snap

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd-pkg-ubuntu#30]
Just a tracking issue for ongoing work. The track has been setup in the store and an experimental snapcraft.yaml has been written, but integration for LXD networking still remains to be done.

**Comment by stgraber** [comment]
We now have a build available in edge and candidate, so one of those two:
 - snap install lxd --channel=2.0/edge
 - snap install lxd --channel=2.0/candidate

Should work. There's still some work needed around network configuration, but at least a basic config will be setup by "lxd init" now.

**Comment by stgraber** [comment]
@dann1

**Comment by dann1** [comment]
Nice. So, no stable channel until network gets completely fixed?

**Comment by stgraber** [comment]
correct
