### ISSUE TITLE
Autostart with systemd not enabled

### ISSUE THREAD

**Issue by sscherfke** [lxc/lxd-pkg-ubuntu#6]
When I install lxd via the PPA on Ubuntu Trusty, upstarts starts lxd and all containers automatically on boot.

WhenI install lxd via the PPA on Ubuntu Vivid, systemd does *not* start lxd automatically on boot. 

The systemd service is correctly installed under `/lib/systemd/system/lxd.service` but it is not linked to `/etc/systemd/system/multi-user.target.wants/`. If I manually `ln -s /lib/systemd/system/lxd.service /etc/systemd/system/multi-user.target.wants/lxd.service`, everything works as expected.

Shouldn't that link be created automatically when I install the package on Ubuntu Vivid?

**Comment by sscherfke** [comment]
`lxd.service`’s `[Install]` section also lacks the line `WantedBy=multi-user.target`.  If that line was present, `systemctl enable lxd` would also work.

**Comment by stgraber** [comment]
Does lxd start when you issue a lxc command, say "lxc list"?

Under systemd, lxd is meant NOT to start on boot but instead be socket-activated.

**Comment by sscherfke** [comment]
Yep, `lxc list` issues a start of my containers.

Why is it meant to be socket-activated? (And why is this not document? ;-))

**Comment by stgraber** [comment]
The fact that containers don't start when lxd is socket-activated is a bug we're working on.

The reason why we were asked to make it socket-activated is that we intend to ship lxd preinstalled in a bunch of Ubuntu images where the user may not actually use LXD. Having it always running would be a waste of resources.

**Comment by sscherfke** [comment]
Okay, so when the bug is fixed, lxd will autostart when there are containers but not, when there are no containers?

**Comment by stgraber** [comment]
correct

**Comment by sscherfke** [comment]
Thank you very much.  I’d be happy if you could provide a link to the issue so that I can follow it. :)

**Comment by pwr22** [comment]
I still seem to be seeing this behaviour, is this still an issue?

**Comment by tych0** [comment]
What package of lxd are you using?

**Comment by pwr22** [comment]
I was using the ppa from this page


Peter
